## Numpy practice session

In [ ]:
# pip install numpy

In [1]:
# import numpy in j.notebook
import numpy as np

## Creating an array using nupmy library

In [2]:
# 1-D Array
food = np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [3]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [5]:
type(food)

numpy.ndarray

In [6]:
type(price)

numpy.ndarray

In [7]:
len(food)

3

In [8]:
len(price)

3

In [9]:
food[1]

'samosa'

In [10]:
price[2]

5

In [11]:
price[0:]

array([5, 5, 5])

In [12]:
price.mean()

5.0

## Methods

In [13]:
# Zero
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
# Ones
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [15]:
# Empty
np.empty(4)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.86919785e-306])

In [16]:
# Range
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
# Specify range
np.arange(4,24)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23])

In [19]:
# Specific range with interval
np.arange(3,30,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [20]:
# Table of 5
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [21]:
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [25]:
# Line space
np.linspace(0, 10, num=6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [26]:
np.linspace(1,100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [27]:
np.linspace(1,100, num=30)

array([  1.        ,   4.4137931 ,   7.82758621,  11.24137931,
        14.65517241,  18.06896552,  21.48275862,  24.89655172,
        28.31034483,  31.72413793,  35.13793103,  38.55172414,
        41.96551724,  45.37931034,  48.79310345,  52.20689655,
        55.62068966,  59.03448276,  62.44827586,  65.86206897,
        69.27586207,  72.68965517,  76.10344828,  79.51724138,
        82.93103448,  86.34482759,  89.75862069,  93.17241379,
        96.5862069 , 100.        ])

In [28]:
# Specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [29]:
np.ones(50, dtype=np.int32)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [30]:
np.ones(50, dtype=np.int64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
np.ones(50, dtype=np.float32)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
      dtype=float32)

## Array functions

In [2]:
import numpy as np
a = np.array([12,34,67,89,46,28,7.8,5.9,3.0])
a

array([12. , 34. , 67. , 89. , 46. , 28. ,  7.8,  5.9,  3. ])

In [3]:
a.sort()
a

array([ 3. ,  5.9,  7.8, 12. , 28. , 34. , 46. , 67. , 89. ])

In [4]:
b = np.array([10.2,23.7,56.9,19.3])
b

array([10.2, 23.7, 56.9, 19.3])

In [6]:
# Concatenate
c = np.concatenate((a,b))
c

array([ 3. ,  5.9,  7.8, 12. , 28. , 34. , 46. , 67. , 89. , 10.2, 23.7,
       56.9, 19.3])

In [7]:
np.sort(c)

array([ 3. ,  5.9,  7.8, 10.2, 12. , 19.3, 23.7, 28. , 34. , 46. , 56.9,
       67. , 89. ])

In [ ]:
# 2-D Arrays

In [8]:
m = np.array([[2,4,6,8],[9,6,8,4]])
m

array([[2, 4, 6, 8],
       [9, 6, 8, 4]])

In [9]:
np.sort(m)

array([[2, 4, 6, 8],
       [4, 6, 8, 9]])

In [10]:
n = np.array([[3,7,9,3],[2,7,4,0]])
n

array([[3, 7, 9, 3],
       [2, 7, 4, 0]])

In [11]:
# Concatenate
o = np.concatenate((m,n))
o

array([[2, 4, 6, 8],
       [9, 6, 8, 4],
       [3, 7, 9, 3],
       [2, 7, 4, 0]])

In [13]:
o = np.concatenate((m,n), axis=0)
o

array([[2, 4, 6, 8],
       [9, 6, 8, 4],
       [3, 7, 9, 3],
       [2, 7, 4, 0]])

In [15]:
o = np.concatenate((m,n), axis=1)
o

array([[2, 4, 6, 8, 3, 7, 9, 3],
       [9, 6, 8, 4, 2, 7, 4, 0]])

In [16]:
len(o)

2

In [17]:
type(o)

numpy.ndarray

In [31]:
p = np.array([[[1,3,5,7],[9,7,5,3]]
      ,[[7,8,5,3],[7,9,3,1]], 
      [[8,4,2,3],[0,7,5,8]],
     ])
p

array([[[1, 3, 5, 7],
        [9, 7, 5, 3]],

       [[7, 8, 5, 3],
        [7, 9, 3, 1]],

       [[8, 4, 2, 3],
        [0, 7, 5, 8]]])

In [32]:
# To find the number of dimensions
p.ndim

3

In [33]:
p = np.array([[2,3],[4,9],[8,5]])
p

array([[2, 3],
       [4, 9],
       [8, 5]])

In [35]:
p.ndim

2

In [37]:
q = np.array([[[1,3,5,7],[9,7,5,3]]
      ,[[7,8,5,3],[7,9,3,1]]])
q

array([[[1, 3, 5, 7],
        [9, 7, 5, 3]],

       [[7, 8, 5, 3],
        [7, 9, 3, 1]]])

In [38]:
q.ndim

3

In [39]:
# Size(number of elements)
q.size

16

In [42]:
q

array([[[1, 3, 5, 7],
        [9, 7, 5, 3]],

       [[7, 8, 5, 3],
        [7, 9, 3, 1]]])

In [46]:
q.ndim

3

In [41]:
# Shape
q.shape

(2, 2, 4)

In [43]:
p

array([[2, 3],
       [4, 9],
       [8, 5]])

In [45]:
p.ndim

2

In [44]:
p.shape

(3, 2)

In [54]:
# Range
p = np.arange(25) # 5*5
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
# Reshape
b = p.reshape(5,5) # 5*5=25
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
b.ndim

2

In [57]:
# Reshape
np.reshape(p, newshape=(1,25), order='c')

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [59]:
# Convert 1-D into 2-D Array
a = np.array([1,2,4,6,8,9,4,2,7])
a

array([1, 2, 4, 6, 8, 9, 4, 2, 7])

In [60]:
a.shape

(9,)

In [63]:
# Row wise 2-D conversion
b = a[np.newaxis, :]
b

array([[1, 2, 4, 6, 8, 9, 4, 2, 7]])

In [62]:
b.shape

(1, 9)

In [64]:
# Colum wise 2-D conversion
c= a[:,np.newaxis]
c

array([[1],
       [2],
       [4],
       [6],
       [8],
       [9],
       [4],
       [2],
       [7]])

In [68]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
a[3:8]

array([4, 5, 6, 7, 8])

In [70]:
a*4

array([ 4,  8, 12, 16, 20, 24, 28, 32])

In [71]:
a+4

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
a.sum()

36

In [74]:
a.mean()

4.5